AMINO_ACIDS = {
    "A": {"name": "Alanine", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": 1.8},
    "R": {"name": "Arginine", "charge": "positive", "polarity": "polar", "hydrophobicity": -4.5},
    "N": {"name": "Asparagine", "charge": "neutral", "polarity": "polar", "hydrophobicity": -3.5},
    "D": {"name": "Aspartic acid", "charge": "negative", "polarity": "polar", "hydrophobicity": -3.5},
    "C": {"name": "Cysteine", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": 2.5},
    "Q": {"name": "Glutamine", "charge": "neutral", "polarity": "polar", "hydrophobicity": -3.5},
    "E": {"name": "Glutamic acid", "charge": "negative", "polarity": "polar", "hydrophobicity": -3.5},
    "G": {"name": "Glycine", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": -0.4},
    "H": {"name": "Histidine", "charge": "positive", "polarity": "polar", "hydrophobicity": -3.2},
    "I": {"name": "Isoleucine", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": 4.5},
    "L": {"name": "Leucine", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": 3.8},
    "K": {"name": "Lysine", "charge": "positive", "polarity": "polar", "hydrophobicity": -3.9},
    "M": {"name": "Methionine", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": 1.9},
    "F": {"name": "Phenylalanine", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": 2.8},
    "P": {"name": "Proline", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": -1.6},
    "S": {"name": "Serine", "charge": "neutral", "polarity": "polar", "hydrophobicity": -0.8},
    "T": {"name": "Threonine", "charge": "neutral", "polarity": "polar", "hydrophobicity": -0.7},
    "W": {"name": "Tryptophan", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": -0.9},
    "Y": {"name": "Tyrosine", "charge": "neutral", "polarity": "polar", "hydrophobicity": -1.3},
    "V": {"name": "Valine", "charge": "neutral", "polarity": "nonpolar", "hydrophobicity": 4.2},
}
